export * from './generics/api.service';
export * from './generics/autenticacion.service';
export * from './jwt.service';
export * from './generics/inventario.service';
export * from './generics/musculos.service';
export * from './generics/aprendices.service';
export * from './generics/historial-asistencia.service';
export * from './generics/rutinas.service';
export * from './generics/ejercicios.service';